"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 23:17:37.283273

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("warehouse", sa.String(length=64), nullable=False),
        sa.Column("aisle", sa.String(length=64), nullable=False),
        sa.Column("position", sa.String(length=64), nullable=False),
        sa.Column("shelf", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gtin"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("raw_barcode", sa.Text(), nullable=False),
        sa.Column("gs1_hri", sa.Text(), nullable=False),
        sa.Column("elements", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=True),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("sscc", sa.String(length=18), nullable=True),
        sa.Column("lot", sa.String(length=20), nullable=True),
        sa.Column("serial", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("production_date", sa.Date(), nullable=True),
        sa.Column("best_before", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scans_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_gtin"), ["gtin"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_location_id"), ["location_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_lot"), ["lot"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_product_id"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_sku"), ["sku"], unique=False)
        batch_op.create_index(batch_op.f("ix_scans_sscc"), ["sscc"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_sscc"))
        batch_op.drop_index(batch_op.f("ix_scans_sku"))
        batch_op.drop_index(batch_op.f("ix_scans_product_id"))
        batch_op.drop_index(batch_op.f("ix_scans_lot"))
        batch_op.drop_index(batch_op.f("ix_scans_location_id"))
        batch_op.drop_index(batch_op.f("ix_scans_gtin"))
        batch_op.drop_index(batch_op.f("ix_scans_created_at"))

    op.drop_table("scans")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_table("products")
    op.drop_table("locations")
    # ### end Alembic commands ###
