"""stock movements

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 18:56:30.185766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('lot', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('sscc', sa.String(length=18), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_gtin'), ['gtin'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_sscc'), ['sscc'], unique=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=16), server_default='receive', nullable=False))

    # ### end Alembic commands ###

    # Existing scans were receipts: turn the ones that identify an item and a
    # quantity into receive movements, so they show up as stock.
    op.execute(
        """
        INSERT INTO movements
            (created_at, user_id, scan_id, kind, location_id, gtin, lot, expiry_date, sscc,
             quantity, note)
        SELECT created_at, user_id, id, 'receive', location_id, gtin, lot, expiry_date, sscc,
               quantity, ''
        FROM scans
        WHERE gtin IS NOT NULL AND quantity IS NOT NULL AND quantity > 0
        ORDER BY id
        """
    )
    op.execute(
        """
        UPDATE scans SET action = 'log'
        WHERE gtin IS NULL OR quantity IS NULL OR quantity <= 0
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('action')

    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_sscc'))
        batch_op.drop_index(batch_op.f('ix_movements_scan_id'))
        batch_op.drop_index(batch_op.f('ix_movements_location_id'))
        batch_op.drop_index(batch_op.f('ix_movements_gtin'))
        batch_op.drop_index(batch_op.f('ix_movements_created_at'))

    op.drop_table('movements')
    # ### end Alembic commands ###
